language: php
php: 7.1

cache:
  directories:
    - vendor

before_script:
  - phpenv config-rm xdebug.ini

install:
 - composer install --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader

script:
  - php ./go.php && cp -R ./cache/ ./tests/data/cache/ && phpunit -d memory_limit=512m --no-coverage
