language: php
php: 7.1

cache:
  directories:
    - vendor

before_script:
  - phpenv config-rm xdebug.ini
  - pwd
  - curl -o `pwd`/cacert.pem https://curl.haxx.se/ca/cacert.pem

install:
 - composer install --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader

script:
  - php -d openssl.cafile=`pwd`/cacert.pem ./go.php && cp -R ./cache/ ./tests/data/cache/ && phpunit -d memory_limit=512m --no-coverage
