language: php
php: 7.1

cache:
  directories:
    - vendor

before_script:
  - phpenv config-rm xdebug.ini
#  - pwd
#  - curl -so `pwd`/cacert.pem https://curl.haxx.se/ca/cacert.pem
  - curl -si 'https://stt.wiki/w/api.php?disabletoc&redirects&prop=wikitext%7Ctemplates%7Clinks%7Cimages&page=Missions&action=parse&format=json'
  - php -i

install:
 - composer install --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader

script:
  - php ./go.php && cp -R ./cache/ ./tests/data/cache/ && phpunit -d memory_limit=512m --no-coverage
#  - php -d openssl.cafile=`pwd`/cacert.pem ./go.php && cp -R ./cache/ ./tests/data/cache/ && phpunit -d memory_limit=512m --no-coverage
