language: php
php: 7.1

cache:
  directories:
    - vendor

before_script:
  - phpenv config-rm xdebug.ini

install:
 - composer install --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader

script:
  - php ./go.php && cp -R ./cache/ ./tests/data/cache/ && phpunit -d memory_limit=512m --no-coverage

# Currently, on Travis, the GNU cURL SSL issue (gnutls_handshake failed) breaks the build.
# This requires re-compiling PHP runtime, which we can't do on the Travis box.
# We should come back later, to see if the issue has been solved from Travis' side.
